title: Example I/O Pages
description: This lab walks you through the X
theme: just-the-docs

# url: https:/test-steph

aux_links:
  "Example repository for Lab Style Guide": 
    - "https://github.com/StephanieKClark/TestIO"


callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
